# Generated by Django 4.0.6 on 2022-07-20 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=50, verbose_name='툴이름')),
                ('tooltype', models.CharField(max_length=50, verbose_name='툴타입')),
                ('toolcontent', models.TextField(verbose_name='툴내용')),
            ],
        ),
        migrations.CreateModel(
            name='swidea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideaname', models.CharField(max_length=50, verbose_name='아이디어이름')),
                ('ideaphoto', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='아이디어사진')),
                ('ideacontent', models.TextField(verbose_name='아이디어내용')),
                ('ideainterest', models.IntegerField(verbose_name='아이디어관심도')),
                ('ideachoice', models.BooleanField(verbose_name='아이디어찜')),
                ('ideatool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usetool', to='swidea.swtool')),
            ],
        ),
    ]
