# Generated by Django 4.0.6 on 2022-07-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swidea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swidea',
            name='ideatool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='아이디어툴', to='swidea.swtool'),
        ),
    ]
