# Generated by Django 4.0.6 on 2022-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swidea', '0002_alter_swidea_ideatool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swidea',
            name='ideachoice',
            field=models.BooleanField(default=False, verbose_name='아이디어찜'),
        ),
        migrations.AlterField(
            model_name='swidea',
            name='ideaphoto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='아이디어사진'),
        ),
    ]
